import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(__dirname, '../src');

// Recursively get all .ts files
function getAllTypeScriptFiles(dir, baseDir = dir) {
    const files = [];
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        const relativePath = path.relative(baseDir, fullPath);

        if (entry.isDirectory()) {
            files.push(...getAllTypeScriptFiles(fullPath, baseDir));
        } else if (entry.name.endsWith('.ts') && entry.name !== 'index.ts' && entry.name !== 'index.d.ts') {
            files.push(relativePath.replace(/\\/g, '/').replace('.ts', ''));
        }
    }

    return files;
}

const files = getAllTypeScriptFiles(srcDir);

// Generate index.ts content
const indexContent = `// Auto-generated file - do not edit manually
// Generated by scripts/generate-exports.mjs
${files.map(file => `export type * from './${file}.js';`).join('\n')}
`;

// Write index.ts
fs.writeFileSync(
    path.join(srcDir, 'index.ts'),
    indexContent,
    'utf-8'
);

console.log(`✓ Generated index.ts with ${files.length} exports.`);

